package gotestx

// CoverageFile is the default coverage profile generated by Go tests.
const CoverageFile = "coverage.out"

// BuildCoverageArgs builds the go test arguments required to enable coverage.
func BuildCoverageArgs(packages []string) []string {
	args := []string{
		"test",
		"-coverprofile=" + CoverageFile,
		"-covermode=atomic",
	}

	return append(args, packages...)
}

// BuildCoverageOpenCommand creates the command used to open the coverage report.
func BuildCoverageOpenCommand() Command {
	return commandRunner("go", "tool", "cover", "-html="+CoverageFile)
}
