package gotestx

// coverageFile is the default coverage profile generated by Go tests.
const coverageFile = "coverage.out"

// buildCoverageArgs builds the go test arguments required to enable coverage.
func buildCoverageArgs(packages []string) []string {
	args := []string{
		"test",
		"-coverprofile=" + coverageFile,
		"-covermode=atomic",
	}

	return append(args, packages...)
}

// buildCoverageOpenCommand creates the command used to open the coverage report.
func buildCoverageOpenCommand() Command {
	return commandRunner("go", "tool", "cover", "-html="+coverageFile)
}
